# Generated by Django 4.2.6 on 2023-10-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appConcessionaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='marca'),
        ),
    ]
